In [1]:
import pandas as pd

In [2]:
movies = pd.read_csv(r'C:\Users\prati\Downloads\archive\movie.csv')

In [3]:
movies

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
27273,131254,Kein Bund für's Leben (2007),Comedy
27274,131256,"Feuer, Eis & Dosenbier (2002)",Comedy
27275,131258,The Pirates (2014),Adventure
27276,131260,Rentun Ruusu (2001),(no genres listed)
27277,131262,Innocence (2014),Adventure|Fantasy|Horror

In [5]:
movies.shape

(27278, 3)

In [8]:
tags= pd.read_csv(r'C:\Users\prati\Downloads\archive\tag.csv')

In [9]:
tags.shape

(465564, 4)

In [10]:
ratings= pd.read_csv(r'C:\Users\prati\Downloads\archive\rating.csv')

In [12]:
ratings.shape

(20000263, 4)

In [13]:
tags.head()

   userId  movieId            tag            timestamp
0      18     4141    Mark Waters  2009-04-24 18:19:40
1      65      208      dark hero  2013-05-10 01:41:18
2      65      353      dark hero  2013-05-10 01:41:19
3      65      521  noir thriller  2013-05-10 01:39:43
4      65      592      dark hero  2013-05-10 01:41:18

In [15]:
tags.iloc[0]   #iloc --> integer locqtion

userId                        18
movieId                     4141
tag                  Mark Waters
timestamp    2009-04-24 18:19:40
Name: 0, dtype: object

In [16]:
tags.iloc[2]

userId                        65
movieId                      353
tag                    dark hero
timestamp    2013-05-10 01:41:19
Name: 2, dtype: object

In [17]:
row_0 = tags.iloc[2]
row_0

userId                        65
movieId                      353
tag                    dark hero
timestamp    2013-05-10 01:41:19
Name: 2, dtype: object

In [19]:
row_0.index  #index fn --> prints the index of the following rows

Index(['userId', 'movieId', 'tag', 'timestamp'], dtype='object')

In [21]:
print(row_0['userId'])

65